### PR TITLE
Fix #262: Handle non-utf-8 characters on an invalid url request

### LINKED ISSUE #262: invalid byte sequence in UTF-8 in JSON param filtering
See the `application#routing_error (ArgumentError) "invalid byte sequence in UTF-8"` exception emails.

Exception info below -- needs investigation.  

```
An ArgumentError occurred in application#routing_error:

  invalid byte sequence in UTF-8
  config/initializers/filter_parameters.rb:36:in `block in <top (required)>'


-------------------------------
Request:
-------------------------------

  ERROR: Failed to generate exception summary:

  ActionView::Template::Error: invalid byte sequence in UTF-8

  /home/ostaccounts/src/accounts-4b54b4f/config/initializers/filter_parameters.rb:36:in `block in <top (required)>'
  /home/ostaccounts/src/accounts-4b54b4f/lib/json_and_string_parameter_filter.rb:46:in `call'
  /home/ostaccounts/src/accounts-4b54b4f/lib/json_and_string_parameter_filter.rb:46:in `block in run'
  /home/ostaccounts/src/accounts-4b54b4f/lib/json_and_string_parameter_filter.rb:45:in `each'
  /home/ostaccounts/src/accounts-4b54b4f/lib/json_and_string_parameter_filter.rb:45:in `run'
  /home/ostaccounts/src/accounts-4b54b4f/config/initializers/filter_parameters.rb:40:in `block in <top (required)>'
```

Failing line:

```ruby
value_filters = [Proc.new { |value| value =~ /^[^@]+@[^.]+\..+/ }]
```

### PR DESCRIPTION
**Pull request by BryanEliDimas**
This PR fixes bug https://github.com/openstax/accounts/issues/262 where are `routing_error ` occurs with message `"invalid byte sequence in UTF-8"`. 

Previously, file `config/initializers/filter_parameters.rb` did not handle non-utf8 characters. 

I just added method `utf8_encoded` that `encode`s strings into utf8 characters and used it where needed, in that same file.

### CODE REVIEW

File: lib/json_and_string_parameter_filter.rb [hunk 1]
```diff
@@ -40,10 +40,10 @@ def run(param_key, param_value)
       # no need to do anything with param_value as it's nil
     elsif param_value.is_a?(String)
       if param_key =~ @string_regexp
-        param_value.gsub!(/^.*$/, '[FILTERED]')
+        param_value.gsub!(/^.*$/, '[FILTERED]').encode('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '')
       else
         @value_filters.each do |value_filter|
-          param_value.gsub!(/^.*$/, '[FILTERED]') if value_filter.call(param_value)
+          param_value.gsub!(/^.*$/, '[FILTERED]').encode('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '') if value_filter.call(param_value.encode('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: ''))
```
Comment (Dantemss) [inline lib/json_and_string_parameter_filter.rb]: I would probably put `param_value.gsub!(/^.*$/, '[FILTERED]').encode('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '')` in some variable just to avoid writing the same operation 3 times.

**Comment by Dantemss** [comment]
Hmmm now I'm starting to question the need for this JSON filter stuff... But guess I'll merge this PR for now.
